server:
  port: 6680

spring:

  application:
    name: commonService

  jwt:
    secret: K85xyYazjMLe6KbK

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
      show_sql: true
      use_sql_comments: true
    generate-ddl: true
    open-in-view: false

  messages:
    basename: i18n/exception
    encoding: UTF-8

  servlet:
    multipart:
      file-size-threshold: 10MB
      location: /home/alpha/server/upload
      max-file-size: 100MB
      max-request-size: 100MB

jasypt:
  encryptor:
    password: Wnd9nzPf38LmaPYezha2
    bean: jasyptStringEncryptor

db:
  url: jdbc:mysql://127.0.0.1/jayuroun?characterEncoding=utf-8&serverTimezone=Asia/Seoul
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: jayuroun
  password: jayuroun

app:
  allowed-origins: http://localhost:4200
