
server:
  port: 8888

spring:

  application:
    name: restfullmssql

  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    properties.hibernate:
#      hbm2ddl.auto: update
      hbm2ddl.auto: create-drop
      format_sql: true
      show_sql: true
      use_sql_comments: true
    generate-ddl: true
    open-in-view: false

  datasource:
    url: jdbc:sqlserver://10.0.10.108:6539;databaseName=test;encrypt=false;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: test
    password: test1234

  messages:
    basename: i18n/exception
    encoding: UTF-8
