# Option
# https://goodgid.github.io/Spring-Boot-SQL-Option
# https://goodgid.github.io/Spring-Boot-SQL-Option-Show-SQL

spring:
  datasource:
    url: ${db2.url}
    username: ${db2.username}
    password: ${db2.password}
    driver-class-name: ${db2.driver-class-name}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB105Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true # to System OutDataSourceConfiguration
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul # @CreatedDate 필드의 Time Zone 값 설정
    generate-ddl: true
    open-in-view: false
